package com.edelweiss.software.tailnumber.server.importer.faa.master

data class MasterRecord(
    val nNumber: String,
    val serialNumber: String,
    val mfrMdlCode: String,
    val engMfrMdl: String?,
    val yearMfr: Int?,
    val typeRegistrant: Int?,
    val name: String?,
    val street: String?,
    val street2: String?,
    val city: String?,
    val state: String?,
    val zipCode: String?,
    val region: Char?,
    val county: Int?,
    val country: String?,
    val lastActionDate: String,
    val certIssueDate: String?,
    val certification: String?,
    val typeAircraft: Char,
    val typeEngine: Int,
    val statusCode: String,
    val modeSCode: String,
    val fractOwner: String?,
    val airWorthDate: String?,
    val otherNames1: String?,
    val otherNames2: String?,
    val otherNames3: String?,
    val otherNames4: String?,
    val otherNames5: String?,
    val expirationDate: String?,
    val uniqueId: String,
    val kitMfr: String?,
    val kitModel: String?,
    val modeSCodeHex: String
)
